### ISSUE TITLE
/bin/sh: 0: can't access tty; job control turned off

### ISSUE THREAD

**Issue by Jonathon52306** [shaowenchen/debugger-action#20]
/bin/sh: 0: can't access tty; job control turned off

**Comment by rysinal** [comment]
me too

**Comment by shaowenchen** [comment]
Can you paste the YAML of workflows?

There are some examples https://github.com/shaowenchen/debugger-action/tree/main/.github/workflows.

**Comment by rysinal** [comment]
> Can you paste the YAML of workflows?
> 
> There are some examples https://github.com/shaowenchen/debugger-action/tree/main/.github/workflows.

https://kubesphere.com.cn/forum/d/3523-github-actions-kind-7-kubesphere

**Comment by shaowenchen** [comment]
> > Can you paste the YAML of workflows?
> > There are some examples https://github.com/shaowenchen/debugger-action/tree/main/.github/workflows.
> 
> https://kubesphere.com.cn/forum/d/3523-github-actions-kind-7-kubesphere

![image](https://user-images.githubusercontent.com/43693241/105125221-d4a62b00-5b16-11eb-83fb-929ed3fb970a.png)

It looks good.

**Comment by shaowenchen** [comment]
Can you post the address of the GitHub repo?

**Comment by rysinal** [comment]
> Can you post the address of the GitHub repo?

https://github.com/rysinal/kstestaction

**Comment by shaowenchen** [comment]
> > Can you post the address of the GitHub repo?
> 
> https://github.com/rysinal/kstestaction

![image](https://user-images.githubusercontent.com/43693241/105142232-5442f280-5b35-11eb-9875-54cd484b1083.png)

Where do you get this error log? I can't find them.

**Comment by rysinal** [comment]
> > > Can you post the address of the GitHub repo?
> > 
> > 
> > https://github.com/rysinal/kstestaction
> 
> ![image](https://user-images.githubusercontent.com/43693241/105142232-5442f280-5b35-11eb-9875-54cd484b1083.png)
> 
> Where do you get this error log? I can't find them.

i get this exception from use xshell and ssh command  connect 2.tcp.ngrok.io' (port 12533)

**Comment by shaowenchen** [comment]
MobaXterm\Putty is ok.  It doesn't support Xshell.

**Comment by rysinal** [comment]
> MobaXterm\Putty is ok. It doesn't support Xshell.

putty is ok,tks

**Comment by shaowenchen** [comment]
iTerm(macOS) and Linux Shell are both OK.

**Comment by Jonathon52306** [comment]
> Can you post the address of the GitHub repo?

https://github.com/Jonathon52306/debugger

**Comment by shaowenchen** [comment]
> > Can you post the address of the GitHub repo?
> 
> https://github.com/Jonathon52306/debugger

Please login with a different shell tool, such as Putty.

**Comment by utfvq88527444** [comment]
putty is not okay on my computer
![image](https://user-images.githubusercontent.com/89308037/151691974-ea8b870c-6cfe-4c6d-bfda-326c51922374.png)

**Comment by utfvq88527444** [comment]
Although the error still exists, I can input my commands in it. But XShell cannot.
