### ISSUE TITLE
登录密码

### ISSUE THREAD

**Issue by ilaipi** [shaowenchen/debugger-action#61]
想问一下登录是登录到action执行时分配的那个ubuntu-latest服务器上吗？

如果是的话，root密码root是在哪里设置的呢？
谢谢🙏

**Comment by shaowenchen** [comment]
会登录到运行 action 的服务器，无法设置登录密码，目前仅能通过默认密码 root 登录。

**Comment by ilaipi** [comment]
root用户默认密码是 root，这个是哪里知道的呢？

**Comment by ilaipi** [comment]
FRP_TOKEN  不传可以不？

**Comment by shaowenchen** [comment]
> root用户默认密码是 root，这个是哪里知道的呢？

readme ，项目首页有写

**Comment by shaowenchen** [comment]
> FRP_TOKEN 不传可以不？

这个要传，用来注册服务用，可以配置在 Settings 中，不会泄露

**Comment by ilaipi** [comment]
我看了一下源码，sshd是自己安装的。我网上没查到资料，感觉应该是自己安装sshd之后，默认密码是root？

我自己根据你这个的原理，做了个代理v2ray的，可以做临时的T子。

[ilaipi/frp-v2ray](https://github.com/ilaipi/frp-v2ray)

**Comment by shaowenchen** [comment]
你是个人才
